have_fun: true

ignore_patterns:
  - "pnpm-lock.yaml"
  - "node_modules/**"
  - ".next/**"
  - "public/**"

code_review:
  disable: false
  comment_severity_threshold: "MEDIUM"
  max_review_comments: 10
  pull_request_opened:
    help: true
    summary: true
    code_review: true
    include_drafts: false
